Repository TestableIO/System.IO.Abstractions, pull requests merged in 2018-07, with the labels that each got.

#294 Fix/disable tests that fail on Unix
  TestHelpers.Tests/MockDirectoryGetAccessControlTests.cs
  TestHelpers.Tests/MockDirectoryInfoTests.cs
  TestHelpers.Tests/MockDirectorySetAccessControlTests.cs
  TestHelpers.Tests/MockDirectoryTests.cs
  TestHelpers.Tests/MockDriveInfoFactoryTests.cs
  TestHelpers.Tests/MockDriveInfoTests.cs
  TestHelpers.Tests/MockFileAppendAllLinesTests.cs
  TestHelpers.Tests/MockFileAppendAllTextTests.cs
  TestHelpers.Tests/MockFileCreateTests.cs
  TestHelpers.Tests/MockFileGetAccessControlTests.cs
  TestHelpers.Tests/MockFileInfoTests.cs
  TestHelpers.Tests/MockFileOpenTests.cs
  TestHelpers.Tests/MockFileSetAccessControlTests.cs
  TestHelpers.Tests/MockFileSystemTests.cs
  TestHelpers.Tests/MockFileTests.cs
  TestHelpers.Tests/MockFileWriteAllBytesTests.cs
  TestHelpers.Tests/MockFileWriteAllLinesTests.cs
  TestHelpers.Tests/MockFileWriteAllTextTests.cs
  TestingHelpers/MockDirectory.cs
  TestingHelpers/MockDirectoryInfo.cs
Labels: bug

#282 Fixed the Problem with .Net Standard 2.0
  System.IO.Abstractions/System.IO.Abstractions.csproj
  TestingHelpers/TestingHelpers.csproj
Labels: waiting-for-author

#177 Add FileStreamFactory and support for mocking FileStreams
  System.IO.Abstractions/FileStreamFactory.cs
  System.IO.Abstractions/FileSystem.cs
  System.IO.Abstractions/IFileStreamFactory.cs
  System.IO.Abstractions/IFileSystem.cs
  System.IO.Abstractions/System.IO.Abstractions.csproj
  System.IO.Abstractions/System.IO.Abstractions.nuspec
  TestHelpers.Tests/MockFileStreamFactoryTests.cs
  TestingHelpers/MockFileStreamFactory.cs
  TestingHelpers/MockFileSystem.cs
  TestingHelpers/TestingHelpers.csproj
Labels: enhancement

#138 Added TestingHelper for directory SetAttributes
  TestHelpers.Tests/MockFileSetAttributesTests.cs
  TestingHelpers/MockFile.cs
  TestingHelpers/MockFileSystem.cs
Labels: waiting-for-author
